version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    parallelism: 4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run linter
          command: |
            . venv/bin/activate
            circleci tests glob **/events/*.py | circleci tests split --split-by=timings --timings-type=classname | xargs flake8
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            circleci tests glob **/tests/*_test.py | circleci tests split --split-by=timings --timings-type=classname | xargs python3 -m unittest

      - store_artifacts:
          path: test-reports
          destination: test-reports