version: 2
jobs:
  
  lint:
    docker:
      - image: circleci/python:3.6.8

    parallelism: 4

    steps:
      - checkout

      - restore_cache:
          keys:
            - lint-dependencies-{{ checksum "requirements.txt" }}
            - lint-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8

      - save_cache:
          paths:
            - ./venv
          key: lint-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run linter
          command: |
            . venv/bin/activate
            circleci tests glob **/events/*.py | circleci tests split --split-by=timings | xargs flake8 --output-file lint-reports
      
      - store_artifacts:
          path: lint-reports
          destination: lint-reports
  
  test:
    docker:
      - image: circleci/python:3.7.3
    
    parallelism: 4

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pytest tests --circleci-parallelize
      
      - store_test_results:
          path: test-results
          

workflows:
  version: 2
  lint-and-test: 
    jobs:
      - lint
      - test:
          requires:
            - lint