version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    parallelism: 4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            TESTFILES=$(circleci tests glob “tests/**_test.py”)
            echo $TESTFILES
            python -W ignore -m unittest ${TESTFILES}

      - store_artifacts:
          path: test-reports
          destination: test-reports