event_source_map = {
    'ans': 'Audubon Naturalist Society',
    'arlington': "Arlington Parks",
    'aws': "Anacostia Watershed Society",
    'casey_trees': "Casey Trees",
    'city_blossoms': "City Blossoms",
    'dc_audubon': "DC Audubon",
    'eleventh_street': "Building Bridges Across the River",
    'fairfax': "Fairfax Parks",
    'fona': "Friends of the National Arboretum",
    'friends_of_kenilworth_gardens': "Friends of Kenilworth Gardens",
    'lfwa': "Little Falls Watershed Alliance",
	'mdflora': "Maryland Native Plant Society",
    'montgomery': "Montgomery Parks",
    'nova_parks': "NOVA Parks",
    'nps': "National Park Service",
    'nva_audubon_society': "Audubon Society of Northern Virginia",
    'potomac_conservancy': "Potomac Conservancy",
    'rcc': "Rock Creek Conservancy",
    'riverkeeper': "Anacostia Riverkeeper",
    'sierra_club_md': "Sierra Club MD",
    'sierra_club': "Sierra Club DC",
    'tnc': "The Nature Conservancy (Virginia)",
    'us_botanic_garden': "United States Botanic Garden",
    'vnps': "Virginia Native Plant Society"
}